
Ext.define('NFW2.view.NFW2_trafficTracker_ipsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.nfw2_traffictracker_ips',

    data: {
        date: __zen('date'),
        today: __zen('today'),
        yesterday: __zen('yesterday'),
        day: __zen('day'),
        one_month: __zen('one_month'),
        month: __zen('month'),
        specific_date: __zen('specific_date'),
        time: __zen('time'),
        output_count: __zen('output_count'),
        action: __zen('action'),
        search: __zen('search'),
        search_methods: __zen('search_methods'),
        end_date: __zen('end_date'),
        start_date: __zen('start_date'),
        search_option: __zen('search_option'),
        task_section: __zen('task_section'),
        search_purpose: __zen('search_purpose'),
        detail_search: __zen('detail_search'),
        step: __zen('step'),
        del: __zen('del'),
        port: __zen('port'),
        protocol: __zen('protocol'),
        search_reset: __zen('search_reset'),
        cum_usage: __zen('cum_usage'),
        cum_session: __zen('cum_session'),
        cum_packet: __zen('cum_packet'),
        src: __zen('src'),
        dest: __zen('dest'),
        service: __zen('service'),
        country_code: __zen('country_code'),
        option: __zen('option'),
        alignment_methods: __zen('alignment_methods'),
        align_criteria: __zen('align_criteria'),
        ips_profile: __zen('ips_profile'),
        hazard: __zen('hazard'),
        fsid_name: __zen('fsid_name'),
        profile: __zen('profile'),
        attacker: __zen('attacker'),
        attack_dest: __zen('attack_dest'),
        fsid: __zen('fsid'),
        detect_counts: __zen('detect_counts'),
        block_counts: __zen('block_counts'),
        detect_byte: __zen('detect_bytes'),
        block_byte: __zen('block_byte')
    }

});