
Ext.define('NFW2.view.NFW2_trafficTracker_apViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.nfw2_traffictracker_ap',

    data: {
        date: __zen('date'),
        today: __zen('today'),
        yesterday: __zen('yesterday'),
        day: __zen('day'),
        one_month: __zen('one_month'),
        month: __zen('month'),
        specific_date: __zen('specific_date'),
        time: __zen('time'),
        output_count: __zen('output_count'),
        action: __zen('action'),
        search: __zen('search'),
        search_methods: __zen('search_methods'),
        end_date: __zen('end_date'),
        start_date: __zen('start_date'),
        search_option: __zen('search_option'),
        task_section: __zen('task_section'),
        zone: __zen('zone'),
        search_purpose: __zen('search_purpose'),
        detail_search: __zen('detail_search'),
        step: __zen('step'),
        del: __zen('del'),
        port: __zen('port'),
        protocol: __zen('protocol'),
        search_reset: __zen('search_reset'),
        cum_usage: __zen('cum_usage'),
        cum_session: __zen('cum_session'),
        cum_packet: __zen('cum_packet'),
        src: __zen('src'),
        dest: __zen('dest'),
        service: __zen('service'),
        sec_policy: __zen('sec_policy'),
        source_country: __zen('source_country'),
        dest_country: __zen('dest_country'),
        option: __zen('option'),
        alignment_methods: __zen('alignment_methods'),
        align_criteria: __zen('align_criteria'),
        application_name: __zen('application_name'),
        categorys: __zen('categorys'),
        technology: __zen('technology'),
        purpose: __zen('purpose')
    }

});