
Ext.define('NFW2.view.win_ipsecViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.win_ipsec',

    data: {
        ipsec_security: __zen('ipsec_security'),
        basic_setting: __zen('basic_setting'),
        detail_setting: __zen('detail_setting'),
        name: __zen('name'),
        inter: __zen('inter'),
        version: __zen('version'),
        authby: __zen('authby'),
        ip_domain: __zen('ip_domain'),
        local_sechost: __zen('local_sechost'),
        remote_sechost: __zen('remote_sechost'),
        protocol: __zen('protocol'),
        port: __zen('port'),
        mode: __zen('mode'),
        operating: __zen('operating'),
        algorithm: __zen('algorithm'),
        key_group: __zen('key_group'),
        local_id_type: __zen('local_id_type'),
        remote_id_type: __zen('remote_id_type'),
        expiration_date: __zen('expiration_date'),
        dpd_info1: __zen('dpd_info1'),
        dpd_info2: __zen('dpd_info2'),
        dpd_info3: __zen('dpd_info3'),
        set: __zen('set'),
        pw_protocol: __zen('pw_protocol'),
        ipsec_info1: __zen('ipsec_info1'),
        udp_force: __zen('udp_force'),
        ipsec_info2: __zen('ipsec_info2'),
        replay_protection: __zen('replay_protection'),
        pfs: __zen('pfs'),
        xauth: __zen('xauth'),
        xauth_server: __zen('xauth_server'),
        virtual_ip: __zen('virtual_ip'),
        auth_method: __zen('auth_method'),
        ipsec_info3: __zen('ipsec_info3'),
        ipsec_info4: __zen('ipsec_info4'),
        id: __zen('id'),
        pwd: __zen('pwd'),
        toggle_on: __zen('toggle_on'),
        toggle_off: __zen('toggle_off'),
        confirm: __zen('confirm'),
        cancel: __zen('cancel')
    }

});